### ISSUE TITLE
Python 2 compatibility

### ISSUE THREAD

**Issue by pwab** [pwab/godot-search#1]
Refactor the code to get the script working with both versions of python.

- [x] print statement
- [x] what else?
	- [x] imports
	- [x] urllib

**Comment by pwab** [comment]
# Travis CI

```
File "godot-search/gdsearch.py", line 20

SyntaxError:
Non-ASCII character '\xe2' in file godot-search/gdsearch.py on line 20, 
but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by pwab** [comment]
**Travis CI**
Python 2.x

```
Traceback (most recent call last):

  File "godot-search/gdsearch.py", line 8, in <module>

    import urllib.parse

ImportError: No module named parse
```
